#!/bin/sh

# Manual pages to own Launchpad.net (on Russian):
# http://ky6uk.org/launchpad-its-really-simple
# http://spolab.ru/laboratory/articles/82-sozdanie-deb-paketov-pervye-shagi-v-ppa
# http://askubuntu.com/questions/90764/how-do-i-create-a-deb-package-for-a-single-python-script
# http://help.ubuntu.ru/wiki/%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_ppa

#gpg --import ./keys.all
#gpg --gen-key
#gpg --fingerprint 31EAF4D7
#gpg --send-keys --keyserver keyserver.ubuntu.com 31EAF4D7
#gpg --export > ./keys.all
#https://launchpad.net/~galyuk/+editpgpkeys
#nano message.txt
gpg --decrypt message.txt

