#!/bin/sh

set -e

    case "$1" in
    configure)

    echo "Setting rights to /opt/pandora/base..." >&2
    chmod -R a+rw /opt/pandora/base
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
    echo "Postinst called with unknown argument \`$1'" >&2

    exit 1
    ;;

    esac

exit 0

